name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version Tag'
        required: false
        default: '1.3.0-bundle'

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-18.04', 'windows-latest' ] # 'ubuntu-latest' "ubuntu-18.04" "windows-latest"
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]

    runs-on: ${{ matrix.os }}

    name: ${{ github.event.inputs.tag }} python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Switch to Workspace
        run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}

      # install prerequisites
      - name: Preqrequisites Ubuntu-18.04
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo apt install -q -y curl software-properties-common build-essential
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-add-repository https://packages.microsoft.com/ubuntu/18.04/prod
          env DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y sudo -E apt install -q -y  libk4a1.4-dev

      - name: Preqrequisites Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install wget --no-progress
          $ProgressPreference = 'SilentlyContinue'
          wget https://download.microsoft.com/download/3/d/6/3d6d9e99-a251-4cf3-8c6a-8e108e960b4b/Azure%20Kinect%20SDK%201.4.1.exe -O sdk.exe
          echo "installing Azure Kinect SDK..."
          ./sdk.exe  /install /passive /norestart /log ${{ github.workspace }}/azurelog.txt
          Wait-Process -Name "sdk" -Timeout 360
          cat ${{ github.workspace }}/azurelog.txt

      # run build command
      - name: Build pyk4a
        run: |
          python -m pip install wheel numpy
          python setup.py bdist_wheel
          ls dist

      # fix many-linux
      - name: Preqrequisites Ubuntu-18.04
        if: matrix.os == 'ubuntu-18.04'
        run: |
          pip install auditwheel

          # get path of first wheel
          files=(dist/*)
          wheel_file="${files[0]}"

          # repaire wheel
          auditwheel repair $wheel_file

          # remove original wheel
          rm $wheel_file

      # upload dist
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.whl
          tag: ${{ github.event.inputs.tag }}
          release_name: "Version ${{ github.event.inputs.tag }}"
          body: "Prebuilt pyk4a wheel packages version ${{ github.event.inputs.tag }}."
          overwrite: true
          file_glob: true
